{
 "title": "Envoy Table",
 "description": "Envoy proxy monitoring Dashboard with service level templates.",
 "tags": [
  "Envoy",
  "Prometheus"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(envoy_server_state{}, namespace)"
   },
   {
    "name": "service_name",
    "label": "Service name",
    "query": "label_values(envoy_server_state{namespace=\"$namespace\"},  container)"
   },
   {
    "name": "pod_name",
    "label": "Pod name",
    "query": "label_values(envoy_server_state{namespace=\"$namespace\", container=\"$service_name\"}, pod)"
   },
   {
    "name": "inter",
    "label": "Sampling",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "State $pod_name",
   "type": "singlestat",
   "description": "Current State of the Server $pod_name",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "repeat": "pod_name",
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "envoy_server_state{namespace=\"$namespace\", container=\"$service_name\", pod=\"$pod_name\"}"
    }
   ]
  },
  {
   "title": "Uptime: $pod_name",
   "type": "singlestat",
   "description": "Shows selected service uptime $pod_name",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "repeat": "pod_name",
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "envoy_server_uptime{namespace=\"$namespace\", container=\"$service_name\", pod=\"$pod_name\"}"
    }
   ]
  },
  {
   "title": "Number of worker threads $pod_name",
   "type": "singlestat",
   "description": "Number of worker threads $pod_name",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "repeat": "pod_name",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "envoy_server_concurrency{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}"
    }
   ]
  },
  {
   "title": "Total connections of Envoy process $pod_name",
   "type": "singlestat",
   "description": "Total connections of both new and old Envoy processes $pod_name",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "repeat": "pod_name",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "envoy_server_total_connections{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}"
    }
   ]
  },
  {
   "title": "Active (warmed) clusters $pod_name",
   "type": "singlestat",
   "description": "Number of currently active (warmed) clusters $pod_name",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "repeat": "pod_name",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "envoy_cluster_manager_active_clusters{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}"
    }
   ]
  },
  {
   "title": "Current number of degraded clusters $pod_name",
   "type": "singlestat",
   "description": "Current number of degraded clusters $pod_name",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 4 },
   "repeat": "pod_name",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(envoy_cluster_membership_degraded{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"})"
    }
   ]
  },
  {
   "title": "Warming (not active) clusters $pod_name",
   "type": "singlestat",
   "description": "Number of currently warming (not active) clusters $pod_name",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 4 },
   "repeat": "pod_name",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "envoy_cluster_manager_warming_clusters{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}"
    }
   ]
  },
  {
   "title": "Days until first cert expiring $pod_name",
   "type": "singlestat",
   "description": "Days until first cert expiring $pod_name",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 4 },
   "repeat": "pod_name",
   "format": "d",
   "valueName": "current",
   "targets": [
    {
     "expr": "envoy_server_days_until_first_cert_expiring{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}"
    }
   ]
  },
  {
   "title": "CPU Usage: $pod_name",
   "type": "graph",
   "description": "Summary of CPU usage by pod $pod_name.\n\nThe red line shows limit of CPUs usage for the process.\n\nThe values is indicated in Millicores. It is a special Kubernates metric means CPU core split into 1000 units.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 7 },
   "repeat": "pod_name",
   "yaxes": [
    { "format": "short", "label": "Millicores" }
   ],
   "targets": [
    {
     "alias": "usage",
     "expr": "rate(container_cpu_usage_seconds_total{container=\"$service_name\", pod=\"$pod_name\", namespace=\"$namespace\"}[$inter])",
     "legendFormat": "usage",
     "measurement": "cpu/usage_rate",
     "tags": [
      { "key": "type", "operator": "=", "value": "pod_container" },
      { "condition": "AND", "key": "namespace_name", "operator": "=~", "value": "/$namespace$/" },
      { "condition": "AND", "key": "pod_name", "operator": "=~", "value": "/$podname$/" }
     ]
    },
    {
     "alias": "limit",
     "expr": "kube_pod_container_resource_limits_cpu_cores{container=\"$service_name\", exported_pod=\"$pod_name\", exported_namespace=\"$namespace\"}",
     "legendFormat": "limit",
     "measurement": "cpu/usage_rate",
     "tags": [
      { "key": "type", "operator": "=", "value": "pod_container" },
      { "condition": "AND", "key": "namespace_name", "operator": "=~", "value": "/$namespace$/" },
      { "condition": "AND", "key": "pod_name", "operator": "=~", "value": "/$podname$/" }
     ]
    },
    {
     "alias": "request",
     "expr": "kube_pod_container_resource_requests_cpu_cores{container=\"$service_name\", exported_pod=\"$pod_name\", exported_namespace=\"$namespace\"}",
     "legendFormat": "request",
     "measurement": "cpu/usage_rate",
     "tags": [
      { "key": "type", "operator": "=", "value": "pod_container" },
      { "condition": "AND", "key": "namespace_name", "operator": "=~", "value": "/$namespace$/" },
      { "condition": "AND", "key": "pod_name", "operator": "=~", "value": "/$podname$/" }
     ]
    }
   ]
  },
  {
   "title": "Commited Memory $pod_name",
   "type": "graph",
   "description": "The amount of used memory",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 7 },
   "repeat": "pod_name",
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "Heap",
     "expr": "kube_pod_container_resource_limits_memory_bytes{exported_namespace=\"$namespace\", container=\"$service_name\", exported_pod=\"$pod_name\"}",
     "legendFormat": "Limits"
    },
    {
     "alias": "Non Heap : Code Cache",
     "expr": "container_memory_max_usage_bytes{namespace=\"$namespace\", container=\"$service_name\", pod=\"$pod_name\"}",
     "legendFormat": "Usage"
    },
    {
     "alias": "Non Heap : Code Cache",
     "expr": "envoy_server_memory_heap_size{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}",
     "legendFormat": "Heap"
    },
    {
     "alias": "Non Heap : Code Cache",
     "expr": "go_memstats_mcache_sys_bytes{namespace=\"$namespace\", container=\"$service_name\", pod=\"$pod_name\"}",
     "legendFormat": "Non Heap"
    }
   ]
  },
  {
   "title": "Total Connections $pod_name",
   "type": "graph",
   "description": "Total active connections $pod_name",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "repeat": "pod_name",
   "yaxes": [
    { "format": "short", "label": "Connections" }
   ],
   "targets": [
    {
     "expr": "sum(increase(envoy_cluster_upstream_cx_total{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}[$inter]))",
     "legendFormat": "Upstream connections"
    },
    {
     "alias": "$tag_envoy_http_conn_manager_prefix",
     "expr": "sum(increase(envoy_http_downstream_cx_total{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}[$inter]))",
     "legendFormat": "Downstream connections"
    }
   ]
  },
  {
   "title": "Envoy Configuration Update Status (xDS) $pod_name",
   "type": "graph",
   "description": "Total amount of cluster updates per second $pod_name",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "repeat": "pod_name",
   "yaxes": [
    { "format": "short", "label": "Operations / sec" }
   ],
   "targets": [
    {
     "alias": "Update successes",
     "expr": "avg(rate(envoy_cluster_update_success{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}[$inter]))",
     "legendFormat": "Update successes"
    },
    {
     "alias": "Update failures",
     "expr": "avg(rate(envoy_cluster_update_failure{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}[$inter]))",
     "legendFormat": "Update failures"
    }
   ]
  },
  {
   "title": "Requests information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Upstream requests per second $pod_name",
     "type": "graph",
     "description": "Upstream requests per second $pod_name",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
     "repeat": "pod_name",
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_envoy_cluster_name",
       "expr": "rate(envoy_cluster_upstream_rq_total{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}[$inter]) OR on() vector(0)",
       "legendFormat": "{{envoy_cluster_name}}"
      }
     ]
    },
    {
     "title": "Upstream requests that were failed due to a connection pool connection failure $pod_name",
     "type": "graph",
     "description": "Upstream requests that were failed due to a connection pool connection failure $pod_name",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
     "repeat": "pod_name",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_envoy_cluster_name",
       "expr": "increase(envoy_cluster_upstream_rq_pending_failure_eject{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}[$inter]) OR on() vector(0)",
       "legendFormat": "{{envoy_cluster_name}}"
      }
     ]
    },
    {
     "title": "Upstream request retries $pod_name",
     "type": "graph",
     "description": "Upstream request retries $pod_name",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
     "repeat": "pod_name",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_envoy_cluster_name",
       "expr": "increase(envoy_cluster_upstream_rq_retry{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}[$inter]) OR on() vector(0)",
       "legendFormat": "{{envoy_cluster_name}}"
      }
     ]
    },
    {
     "title": "Upstream requests in pending $pod_name",
     "type": "graph",
     "description": "Upstream requests in pending $pod_name",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
     "repeat": "pod_name",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_envoy_cluster_name",
       "expr": "increase(envoy_cluster_upstream_rq_pending_active{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}[$inter]) OR on() vector(0)",
       "legendFormat": "{{envoy_cluster_name}}"
      }
     ]
    },
    {
     "title": "Upstream requests cancelled before obtaining a connection pool connection $pod_name",
     "type": "graph",
     "description": "Upstream requests cancelled before obtaining a connection pool connection $pod_name",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 48 },
     "repeat": "pod_name",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_envoy_cluster_name",
       "expr": "increase(envoy_cluster_upstream_rq_cancelled{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}[$inter]) OR on() vector(0)",
       "legendFormat": "{{envoy_cluster_name}}"
      }
     ]
    },
    {
     "title": "Upstream requests that timed out waiting for a response $pod_name",
     "type": "graph",
     "description": "Upstream requests that timed out waiting for a response $pod_name",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 55 },
     "repeat": "pod_name",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_envoy_cluster_name",
       "expr": "increase(envoy_cluster_upstream_rq_timeout{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}[$inter]) OR on() vector(0)",
       "legendFormat": "{{envoy_cluster_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Load balancing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of currently available subsets $pod_name",
     "type": "graph",
     "description": "Number of currently available subsets $pod_name",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
     "repeat": "pod_name",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_envoy_cluster_name",
       "expr": "envoy_cluster_lb_subsets_active{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"} OR on() vector(0)",
       "legendFormat": "{{envoy_cluster_name}}"
      }
     ]
    },
    {
     "title": "Number of times any subset was selected for load balancing $pod_name",
     "type": "graph",
     "description": "Number of times any subset was selected for load balancing $pod_name",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
     "repeat": "pod_name",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_envoy_cluster_name",
       "expr": "increase(envoy_cluster_lb_subsets_selected{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}[$inter]) OR on() vector(0)",
       "legendFormat": "{{envoy_cluster_name}}"
      }
     ]
    },
    {
     "title": "Number of subsets removed due to no hosts $pod_name",
     "type": "graph",
     "description": "Number of subsets removed due to no hosts $pod_name",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
     "repeat": "pod_name",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_envoy_cluster_name",
       "expr": "increase(envoy_cluster_lb_subsets_removed{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}[$inter]) OR on() vector(0)",
       "legendFormat": "{{envoy_cluster_name}}"
      }
     ]
    },
    {
     "title": "Number of requests load balanced with the load balancer in panic mode $pod_name",
     "type": "graph",
     "description": "Number of requests load balanced with the load balancer in panic mode $pod_name",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
     "repeat": "pod_name",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_envoy_cluster_name",
       "expr": "increase(envoy_cluster_lb_healthy_panic{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}[$inter]) OR on() vector(0)",
       "legendFormat": "{{envoy_cluster_name}}"
      }
     ]
    },
    {
     "title": "Number of times the fallback policy was invoked $pod_name",
     "type": "graph",
     "description": "Number of times the fallback policy was invoked $pod_name",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
     "repeat": "pod_name",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_envoy_cluster_name",
       "expr": "increase(envoy_cluster_lb_subsets_fallback{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}[$inter]) OR on() vector(0)",
       "legendFormat": "{{envoy_cluster_name}}"
      }
     ]
    },
    {
     "title": "Number of times ended with random zone selection due to rounding error $pod_name",
     "type": "graph",
     "description": "Number of times ended with random zone selection due to rounding error $pod_name",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 56 },
     "repeat": "pod_name",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_envoy_cluster_name",
       "expr": "increase(envoy_cluster_lb_zone_no_capacity_left{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}[$inter]) OR on() vector(0)",
       "legendFormat": "{{envoy_cluster_name}}"
      }
     ]
    },
    {
     "title": "Number of subsets created $pod_name",
     "type": "graph",
     "description": "Number of subsets created $pod_name",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 63 },
     "repeat": "pod_name",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_envoy_cluster_name",
       "expr": "increase(envoy_cluster_lb_subsets_created{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}[$inter]) OR on() vector(0)",
       "legendFormat": "{{envoy_cluster_name}}"
      }
     ]
    },
    {
     "title": "Number of times the subset panic mode triggered $pod_name",
     "type": "graph",
     "description": "Number of times the subset panic mode triggered $pod_name",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 70 },
     "repeat": "pod_name",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_envoy_cluster_name",
       "expr": "increase(envoy_cluster_lb_subsets_fallback_panic{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}[$inter]) OR on() vector(0)",
       "legendFormat": "{{envoy_cluster_name}}"
      }
     ]
    },
    {
     "title": "Number of invalid hosts passed to original destination load balancer $pod_name",
     "type": "graph",
     "description": "Number of invalid hosts passed to original destination load balancer $pod_name",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 77 },
     "repeat": "pod_name",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_envoy_cluster_name",
       "expr": "increase(envoy_cluster_original_dst_host_invalid{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}[$inter]) OR on() vector(0)",
       "legendFormat": "{{envoy_cluster_name}}"
      }
     ]
    },
    {
     "title": "Number of local host set is not set or it is panic mode for local cluster $pod_name",
     "type": "graph",
     "description": "Number of local host set is not set or it is panic mode for local cluster $pod_name",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 84 },
     "repeat": "pod_name",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_envoy_cluster_name",
       "expr": "increase(envoy_cluster_lb_local_cluster_not_ok{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}[$inter]) OR on() vector(0)",
       "legendFormat": "{{envoy_cluster_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Upstream",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Upstream connections $pod_name",
     "type": "graph",
     "description": "Displays the number of Connections per Second being performed against each Upstream $pod_name",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
     "repeat": "pod_name",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_envoy_cluster_name",
       "expr": "increase(envoy_cluster_upstream_cx_total{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}[$inter]) OR on() vector(0)",
       "legendFormat": "{{envoy_cluster_name}}"
      }
     ]
    },
    {
     "title": "Upstream requests per second $pod_name",
     "type": "graph",
     "description": "Upstream requests per second $pod_name",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
     "repeat": "pod_name",
     "yaxes": [
      { "format": "short", "label": "Request / sec" }
     ],
     "targets": [
      {
       "alias": "$tag_envoy_cluster_name",
       "expr": "rate(envoy_cluster_upstream_rq_total{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}[$inter]) OR on() vector(0)",
       "legendFormat": "{{envoy_cluster_name}}"
      }
     ]
    },
    {
     "title": "Upstream Latency $pod_name",
     "type": "graph",
     "description": "Common response time out of a minute $pod_name",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
     "repeat": "pod_name",
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_envoy_cluster_name",
       "expr": "increase(envoy_cluster_upstream_rq_time_sum{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}[$inter])",
       "legendFormat": "{{envoy_cluster_name}}"
      }
     ]
    },
    {
     "title": "Number of upstream connection failures $pod_name",
     "type": "graph",
     "description": "Number of upstream connection failures $pod_name",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
     "repeat": "pod_name",
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_envoy_cluster_name",
       "expr": "increase(envoy_cluster_upstream_cx_connect_fail{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}[$inter]) OR on() vector(0)",
       "legendFormat": "{{envoy_cluster_name}}"
      }
     ]
    },
    {
     "title": "Number of upstream connection connect timeouts $pod_name",
     "type": "graph",
     "description": "Number of upstream connection connect timeouts $pod_name",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 50 },
     "repeat": "pod_name",
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_envoy_cluster_name",
       "expr": "increase(envoy_cluster_upstream_cx_connect_timeout{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}[$inter]) OR on() vector(0)",
       "legendFormat": "{{envoy_cluster_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Downstream",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Downstream connections $pod_name",
     "type": "graph",
     "description": "Total amount of connections through different connection managers $pod_name",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
     "repeat": "pod_name",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_envoy_http_conn_manager_prefix",
       "expr": "increase(envoy_http_downstream_cx_total{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}[$inter]) OR on() vector(0)",
       "legendFormat": "{{envoy_http_conn_manager_prefix}}"
      }
     ]
    },
    {
     "title": "Downstream requests per second $pod_name",
     "type": "graph",
     "description": "Total amount of downstream requests per second  through connection manager $pod_name",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
     "repeat": "pod_name",
     "yaxes": [
      { "format": "short", "label": "Request / sec" }
     ],
     "targets": [
      {
       "alias": "$tag_envoy_http_conn_manager_prefix",
       "expr": "rate(envoy_http_downstream_rq_total{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}[$inter]) OR on() vector(0)",
       "legendFormat": "{{envoy_http_conn_manager_prefix}}"
      }
     ]
    },
    {
     "title": "Downstream Latency $pod_name",
     "type": "graph",
     "description": "Downstream Latency $pod_name",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 37 },
     "repeat": "pod_name",
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_envoy_http_conn_manager_prefix",
       "expr": "increase(envoy_http_downstream_rq_time_sum{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}[$inter]) OR on() vector(0)",
       "legendFormat": "{{envoy_http_conn_manager_prefix}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Upstream sent/received data per second $pod_name",
     "type": "graph",
     "description": "Upstream sent/received data per second $pod_name",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
     "repeat": "pod_name",
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "Sent",
       "expr": "sum(rate(envoy_cluster_upstream_cx_tx_bytes_total{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}[$inter]))",
       "legendFormat": "Sent"
      },
      {
       "alias": "Received",
       "expr": "-sum(rate(envoy_cluster_upstream_cx_rx_bytes_total{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}[$inter]))",
       "legendFormat": "Received"
      }
     ]
    },
    {
     "title": "Upstream sent/received bytes currently buffered $pod_name",
     "type": "graph",
     "description": "Upstream sent/received bytes currently buffered $pod_name",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
     "repeat": "pod_name",
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "Sent",
       "expr": "sum(increase(envoy_cluster_upstream_cx_tx_bytes_buffered{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}[$inter]))",
       "legendFormat": "Sent"
      },
      {
       "alias": "Received",
       "expr": "sum(rate(envoy_cluster_upstream_cx_rx_bytes_buffered{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}[$inter]))",
       "legendFormat": "Received"
      }
     ]
    },
    {
     "title": "Downstream sent/received data per second $pod_name",
     "type": "graph",
     "description": "Downstream sent/received data per second $pod_name",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
     "repeat": "pod_name",
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "Sent",
       "expr": "sum(rate(envoy_http_downstream_cx_tx_bytes_total{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}[$inter]))",
       "legendFormat": "Sent"
      },
      {
       "alias": "Received",
       "expr": "-sum(rate(envoy_http_downstream_cx_rx_bytes_total{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}[$inter]))",
       "legendFormat": "Received"
      }
     ]
    },
    {
     "title": "Downstream sent/received bytes currently buffered $pod_name",
     "type": "graph",
     "description": "Downstream sent/received bytes currently buffered $pod_name",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
     "repeat": "pod_name",
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "Sent",
       "expr": "sum(rate(envoy_http_downstream_cx_tx_bytes_buffered{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}[$inter]))",
       "legendFormat": "Sent"
      },
      {
       "alias": "Received",
       "expr": "sum(rate(envoy_http_downstream_cx_rx_bytes_buffered{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}[$inter]))",
       "legendFormat": "Received"
      }
     ]
    }
   ]
  },
  {
   "title": "Circuit breakers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Whether the connection circuit breaker is closed  or open for default priority $pod_name",
     "type": "graph",
     "description": "Whether the connection circuit breaker is closed (0) or open (1) for default priority $pod_name",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 25 },
     "repeat": "pod_name",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_envoy_cluster_name",
       "expr": "envoy_cluster_circuit_breakers_default_cx_open{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}",
       "legendFormat": "{{envoy_cluster_name}}"
      }
     ]
    },
    {
     "title": "Whether the requests circuit breaker is closed  or open for default priority $pod_name",
     "type": "graph",
     "description": "Whether the requests circuit breaker is closed (0) or open (1) for default priority $pod_name",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 30 },
     "repeat": "pod_name",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_envoy_cluster_name",
       "expr": "envoy_cluster_circuit_breakers_default_rq_open{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"} OR on() vector(0)",
       "legendFormat": "{{envoy_cluster_name}}"
      }
     ]
    },
    {
     "title": "Whether the connection circuit breaker is closed  or open for high  priority $pod_name",
     "type": "graph",
     "description": "Whether the connection circuit breaker is closed (0) or open (1) for high priority $pod_name",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 35 },
     "repeat": "pod_name",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_envoy_cluster_name",
       "expr": "envoy_cluster_circuit_breakers_high_cx_open{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"} OR on() vector(0)",
       "legendFormat": "{{envoy_cluster_name}}"
      }
     ]
    },
    {
     "title": "Whether the requests circuit breaker is closed  or open for high priority $pod_name",
     "type": "graph",
     "description": "Whether the requests circuit breaker is closed (0) or open (1) for high priority $pod_name",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 40 },
     "repeat": "pod_name",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_envoy_cluster_name",
       "expr": "envoy_cluster_circuit_breakers_high_rq_open{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"} OR on() vector(0)",
       "legendFormat": "{{envoy_cluster_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Dynamic http statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of upstream requests completed $pod_name",
     "type": "graph",
     "description": "Number of upstream requests completed $pod_name",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 26 },
     "repeat": "pod_name",
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_envoy_cluster_name",
       "expr": "increase(envoy_cluster_upstream_rq_completed{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}[$inter]) OR on() vector(0)",
       "legendFormat": "{{envoy_cluster_name}}"
      }
     ]
    },
    {
     "title": "Number of upstream requests completed  with response code 2XX $pod_name",
     "type": "graph",
     "description": "Number of upstream requests completed  with response code 2XX $pod_name",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 32 },
     "repeat": "pod_name",
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_envoy_cluster_name",
       "expr": "increase(envoy_cluster_upstream_rq_xx{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\", envoy_response_code_class=\"2\"}[$inter]) OR on() vector(0)",
       "legendFormat": "{{envoy_cluster_name}}"
      }
     ]
    },
    {
     "title": "Number of upstream requests completed with response code 4XX $pod_name",
     "type": "graph",
     "description": "Number of upstream requests completed with response code 4XX $pod_name",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 38 },
     "repeat": "pod_name",
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_envoy_cluster_name",
       "expr": "increase(envoy_cluster_upstream_rq_xx{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\", envoy_response_code_class=\"4\"}[$inter]) OR on() vector(0)",
       "legendFormat": "{{envoy_cluster_name}}"
      }
     ]
    },
    {
     "title": "Number of upstream requests completed  with response code 5XX $pod_name",
     "type": "graph",
     "description": "Number of upstream requests completed with response code 5XX $pod_name",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 44 },
     "repeat": "pod_name",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_envoy_cluster_name",
       "expr": "increase(envoy_cluster_upstream_rq_xx{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\", envoy_response_code_class=\"5\"}[$inter]) OR on() vector(0)",
       "legendFormat": "{{envoy_cluster_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Dynamic http statistics (internal requests)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of internal upstream requests completed $pod_name",
     "type": "graph",
     "description": "Number of internal upstream requests completed $pod_name",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
     "repeat": "pod_name",
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_envoy_cluster_name",
       "expr": "increase(envoy_cluster_internal_upstream_rq_completed{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}[$inter])",
       "legendFormat": "{{envoy_cluster_name}}"
      }
     ]
    },
    {
     "title": "Number of internal upstream requests completed 2XX $pod_name",
     "type": "graph",
     "description": "Number of internal upstream requests completed 2XX $pod_name",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 33 },
     "repeat": "pod_name",
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_envoy_cluster_name",
       "expr": "increase(envoy_cluster_internal_upstream_rq_xx{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\", envoy_response_code_class=\"2\"}[$inter]) OR on() vector(0)",
       "legendFormat": "{{envoy_cluster_name}}"
      }
     ]
    },
    {
     "title": "Number of internal upstream requests completed 4XX $pod_name",
     "type": "graph",
     "description": "Number of internal upstream requests completed 4XX $pod_name",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 39 },
     "repeat": "pod_name",
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_envoy_cluster_name",
       "expr": "increase(envoy_cluster_internal_upstream_rq_xx{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\", envoy_response_code_class=\"4\"}[$inter]) OR on() vector(0)",
       "legendFormat": "{{envoy_cluster_name}}"
      }
     ]
    },
    {
     "title": "Number of internal upstream requests completed 5XX $pod_name",
     "type": "graph",
     "description": "Number of internal upstream requests completed 5XX $pod_name",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 45 },
     "repeat": "pod_name",
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_envoy_cluster_name",
       "expr": "increase(envoy_cluster_internal_upstream_rq_xx{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\", envoy_response_code_class=\"5\"}[$inter]) OR on() vector(0)",
       "legendFormat": "{{envoy_cluster_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Dynamic http statistics (external requests)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of external upstream requests completed $pod_name",
     "type": "graph",
     "description": "Number of external upstream requests completed $pod_name",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 28 },
     "repeat": "pod_name",
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_envoy_cluster_name",
       "expr": "increase(envoy_cluster_external_upstream_rq_completed{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}[$inter]) OR on() vector(0)",
       "legendFormat": "{{envoy_cluster_name}}"
      }
     ]
    },
    {
     "title": "Number of external upstream requests completed 2XX $pod_name",
     "type": "graph",
     "description": "Number of external upstream requests completed 2XX $pod_name",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 34 },
     "repeat": "pod_name",
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_envoy_cluster_name",
       "expr": "increase(envoy_cluster_external_upstream_rq_xx{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\", envoy_response_code_class=\"2\"}[$inter]) OR on() vector(0)",
       "legendFormat": "{{envoy_cluster_name}}"
      }
     ]
    },
    {
     "title": "Number of external upstream requests completed 4XX $pod_name",
     "type": "graph",
     "description": "Number of external upstream requests completed 4XX $pod_name",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 40 },
     "repeat": "pod_name",
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_envoy_cluster_name",
       "expr": "increase(envoy_cluster_external_upstream_rq_xx{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\", envoy_response_code_class=\"4\"}[$inter]) OR on() vector(0)",
       "legendFormat": "{{envoy_cluster_name}}"
      }
     ]
    },
    {
     "title": "Number of external upstream requests completed 5XX $pod_name",
     "type": "graph",
     "description": "Number of external upstream requests completed 5XX $pod_name",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 46 },
     "repeat": "pod_name",
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_envoy_cluster_name",
       "expr": "increase(envoy_cluster_external_upstream_rq_xx{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\", envoy_response_code_class=\"5\"}[$inter]) OR on() vector(0)",
       "legendFormat": "{{envoy_cluster_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Flow control",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of times the upstream connection backed up and paused reads from downstream $pod_name",
     "type": "graph",
     "description": "Number of times the upstream connection backed up and paused reads from downstream $pod_name",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 29 },
     "repeat": "pod_name",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_envoy_cluster_name",
       "expr": "increase(envoy_cluster_upstream_flow_control_backed_up_total{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}[$inter]) OR on() vector(0)",
       "legendFormat": "{{envoy_cluster_name}}"
      }
     ]
    },
    {
     "title": "Number of times flow control paused reading from upstream $pod_name",
     "type": "graph",
     "description": "Number of times flow control paused reading from upstream $pod_name",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 35 },
     "repeat": "pod_name",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_envoy_cluster_name",
       "expr": "increase(envoy_cluster_upstream_flow_control_paused_reading_total{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}[$inter]) OR on() vector(0)",
       "legendFormat": "{{envoy_cluster_name}}"
      }
     ]
    },
    {
     "title": "Number of times flow control resumed reading from upstream $pod_name",
     "type": "graph",
     "description": "Number of times flow control resumed reading from upstream $pod_name",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 41 },
     "repeat": "pod_name",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_envoy_cluster_name",
       "expr": "increase(envoy_cluster_upstream_flow_control_resumed_reading_total{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}[$inter]) OR on() vector(0)",
       "legendFormat": "{{envoy_cluster_name}}"
      }
     ]
    },
    {
     "title": "Number of times the upstream connection drained and resumed reads from downstream $pod_name",
     "type": "graph",
     "description": "Number of times the upstream connection drained and resumed reads from downstream $pod_name",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 47 },
     "repeat": "pod_name",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_envoy_cluster_name",
       "expr": "increase(envoy_cluster_upstream_flow_control_drained_total{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}[$inter]) OR on() vector(0)",
       "legendFormat": "{{envoy_cluster_name}}"
      }
     ]
    },
    {
     "title": "Number of times failed internal redirects resulted in redirects being passed downstream $pod_name",
     "type": "graph",
     "description": "Number of times the upstream connection drained and resumed reads from downstream $pod_name",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 53 },
     "repeat": "pod_name",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_envoy_cluster_name",
       "expr": "increase(envoy_cluster_upstream_internal_redirect_failed_total{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}[$inter]) OR on() vector(0)",
       "legendFormat": "{{envoy_cluster_name}}"
      }
     ]
    }
   ]
  }
 ]
}