apiVersion: v1
kind: ServiceAccount
metadata:
  name: ratelimit
  labels:
    app: ratelimit
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ratelimit
  labels:
    app: ratelimit
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets", "services", "pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["networking.istio.io"]
  resources: ["envoyfilters", "gateways", "virtualservices"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["security.istio.io"]
  resources: ["requestauthentications", "authorizationpolicies"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["gateway.networking.k8s.io"]
  resources: ["httproutes", "gateways"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ratelimit
  labels:
    app: ratelimit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ratelimit
subjects:
- kind: ServiceAccount
  name: ratelimit
  namespace: {{ .Values.namespace }}