apiVersion: v1
kind: Service
metadata:
  name: ratelimit-service
  labels:
    app: ratelimit
spec:
  selector:
    app: ratelimit
  ports:
  - name: api
    port: {{ .Values.api.port }}
    targetPort: api
  - name: metrics
    port: {{ .Values.metrics.port }}
    targetPort: metrics
  - name: grpc
    port: 8081
    targetPort: 8081
  type: ClusterIP