package org.qubership.remesh;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import lombok.extern.slf4j.Slf4j;
import org.qubership.remesh.handler.Resource;
import org.qubership.remesh.handler.MeshResourceRouter;
import org.qubership.remesh.serialization.YamlPreprocessor;
import org.qubership.remesh.util.ObjectMapperProvider;
import org.qubership.remesh.validation.ResourceValidator;

import java.io.IOException;
import java.io.Writer;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Stream;

@Slf4j
public class TransformerService {
    public static final String FRAGMENT_DELIMITER = "(?m)^---\\s*$";
    public static final String AUTOGENERATED_POSTFIX = "_autogenerated";
    private final YamlPreprocessor yamlPreprocessor;
    private final MeshResourceRouter meshResourceRouter;
    private final ResourceValidator resourceValidator;
    private final ObjectMapper mapper;

    public TransformerService() {
        this(new YamlPreprocessor(ObjectMapperProvider.getMapper()),
                new MeshResourceRouter(),
                new ResourceValidator(),
                ObjectMapperProvider.getMapper()
        );
    }

    public TransformerService(YamlPreprocessor yamlPreprocessor,
                              MeshResourceRouter meshResourceRouter,
                              ResourceValidator resourceValidator,
                              ObjectMapper mapper) {
        this.yamlPreprocessor = yamlPreprocessor;
        this.meshResourceRouter = meshResourceRouter;
        this.resourceValidator = resourceValidator;
        this.mapper = mapper;
    }

    public void transform(Path dir, boolean validate) throws IOException {
        log.info("Start transforming in dir '{}'", dir);
        try (Stream<Path> stream = Files.walk(dir)) {
            stream.filter(Files::isRegularFile)
                    .filter(this::isYaml)
                    .filter(this::isNotAutogenerated)
                    .forEach(file -> processFile(file, validate));
        }
    }

    boolean isYaml(Path p) {
        String name = p.getFileName().toString().toLowerCase();
        return name.endsWith(".yaml") || name.endsWith(".yml");
    }

    boolean isNotAutogenerated(Path p) {
        String name = p.getFileName().toString().toLowerCase();
        return !name.contains(AUTOGENERATED_POSTFIX);
    }

    void processFile(Path file, boolean validate) {
        log.info("=== Processing file '{}' ===", file);

        try {
            List<Resource> allOutputResources = new ArrayList<>();

            String[] fragments = splitByFragments(file);

            int fragmentIndex = 0;
            for (String fragment : fragments) {
                if (fragment == null || fragment.isBlank()) {
                    continue;
                }

                fragmentIndex++;
                log.debug("--- Start processing fragment {} in file '{}'", fragmentIndex, file);
                try {
                    JsonNode node = yamlPreprocessor.readAsJsonNode(fragment);
                    if (node == null) {
                        continue;
                    }

                    List<Resource> resources = meshResourceRouter.route(node);
                    allOutputResources.addAll(resources);
                } finally {
                    log.debug("--- Finished processing fragment {} in file '{}'\n", fragmentIndex, file);
                }
            }

            if (!allOutputResources.isEmpty()) {
//                    Path oldFile = file.resolveSibling(file.getFileName().toString() + "_old");
//                    Files.move(file, oldFile);

                Path newFile = file.resolveSibling(generatedFileName(file));

                int i = 0;
                try (Writer writer = Files.newBufferedWriter(newFile)) {
                    writer.write("# This file was automatically generated from NC Mesh CRs\n\n");
                    for (Resource resource : allOutputResources) {
                        if (validate) {
                            resourceValidator.validateResource(resource);
                        }
                        writer.write("# fragment " + i++ + "\n");
                        writer.write(mapper.writeValueAsString(resource));

                    }
                }

                log.info("=== Output file is '{}' ===\n", newFile);
            }
        }
        catch (IOException e) {
            log.error("Failed to process file '{}'", file, e);
        }
    }

    String[] splitByFragments(Path file) throws IOException {
        String content = Files.readString(file, StandardCharsets.UTF_8);
        return content.split(FRAGMENT_DELIMITER);
    }

    String generatedFileName(Path file) {
        String fileName = file.getFileName().toString();

        int dotIndex = fileName.lastIndexOf('.');
        String name;
        String ext;

        if (dotIndex > 0) {
            name = fileName.substring(0, dotIndex);
            ext = fileName.substring(dotIndex);
        } else {
            name = fileName;
            ext = "";
        }

        return name + AUTOGENERATED_POSTFIX + ext;
    }
}
