name: Go build

on:
  push:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:     
  build:
    uses: netcracker/qubership-core-infra/.github/workflows/go-build-with-sonar.yaml@test/add-env-to-go-build-w-sonar
    with:
      go-module-dir: control-plane
      actor: ${{ github.actor }}
      sonar-project-key: ${{ vars.SONAR_PROJECT_KEY }}
      build-test-service-image: true
    secrets:
      sonar-token: ${{ secrets.SONAR_TOKEN }}
