name: Go build

on:
  push:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  test_service_build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and load test-service image
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: |
            ghcr.io/netcracker/cp-test-service:latest
        context: ./
        file: ./control-plane-test-service/Dockerfile
        platforms: linux/amd64      


  build:
    uses: netcracker/qubership-core-infra/.github/workflows/go-build-with-sonar.yaml@v1.0.5
    with:
      go-module-dir: control-plane
      actor: ${{ github.actor }}
      sonar-project-key: ${{ vars.SONAR_PROJECT_KEY }}
    secrets:
      sonar-token: ${{ secrets.SONAR_TOKEN }}

  docker-build:
    needs: [build]
    uses: netcracker/qubership-core-infra/.github/workflows/docker-build.yaml@v1.0.5
    with:
      dry-run: false
