// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0--rc1
// source: test_bus.proto

package bus

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventType int32

const (
	EventType_RAW_DATA EventType = 0
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "RAW_DATA",
	}
	EventType_value = map[string]int32{
		"RAW_DATA": 0,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_test_bus_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_test_bus_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_test_bus_proto_rawDescGZIP(), []int{0}
}

type Topic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Topic) Reset() {
	*x = Topic{}
	mi := &file_test_bus_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Topic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Topic) ProtoMessage() {}

func (x *Topic) ProtoReflect() protoreflect.Message {
	mi := &file_test_bus_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Topic.ProtoReflect.Descriptor instead.
func (*Topic) Descriptor() ([]byte, []int) {
	return file_test_bus_proto_rawDescGZIP(), []int{0}
}

func (x *Topic) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventType     EventType              `protobuf:"varint,1,opt,name=eventType,proto3,enum=com.netcracker.mesh.v3.test.bus.EventType" json:"eventType,omitempty"`
	Data          *anypb.Any             `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_test_bus_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_test_bus_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_test_bus_proto_rawDescGZIP(), []int{1}
}

func (x *Event) GetEventType() EventType {
	if x != nil {
		return x.EventType
	}
	return EventType_RAW_DATA
}

func (x *Event) GetData() *anypb.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

type RawBytesData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawBytesData) Reset() {
	*x = RawBytesData{}
	mi := &file_test_bus_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawBytesData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawBytesData) ProtoMessage() {}

func (x *RawBytesData) ProtoReflect() protoreflect.Message {
	mi := &file_test_bus_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawBytesData.ProtoReflect.Descriptor instead.
func (*RawBytesData) Descriptor() ([]byte, []int) {
	return file_test_bus_proto_rawDescGZIP(), []int{2}
}

func (x *RawBytesData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_test_bus_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_test_bus_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_test_bus_proto_rawDescGZIP(), []int{3}
}

var File_test_bus_proto protoreflect.FileDescriptor

const file_test_bus_proto_rawDesc = "" +
	"\n" +
	"\x0etest_bus.proto\x12\x1fcom.netcracker.mesh.v3.test.bus\x1a\x19google/protobuf/any.proto\"\x1b\n" +
	"\x05Topic\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"{\n" +
	"\x05Event\x12H\n" +
	"\teventType\x18\x01 \x01(\x0e2*.com.netcracker.mesh.v3.test.bus.EventTypeR\teventType\x12(\n" +
	"\x04data\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x04data\"\"\n" +
	"\fRawBytesData\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\a\n" +
	"\x05Empty*\x19\n" +
	"\tEventType\x12\f\n" +
	"\bRAW_DATA\x10\x002\xd4\x01\n" +
	"\fTestEventBus\x12_\n" +
	"\tSubscribe\x12&.com.netcracker.mesh.v3.test.bus.Topic\x1a&.com.netcracker.mesh.v3.test.bus.Event\"\x000\x01\x12c\n" +
	"\x0fGetLastSnapshot\x12&.com.netcracker.mesh.v3.test.bus.Empty\x1a&.com.netcracker.mesh.v3.test.bus.Event\"\x00B\aZ\x05.;busb\x06proto3"

var (
	file_test_bus_proto_rawDescOnce sync.Once
	file_test_bus_proto_rawDescData []byte
)

func file_test_bus_proto_rawDescGZIP() []byte {
	file_test_bus_proto_rawDescOnce.Do(func() {
		file_test_bus_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_test_bus_proto_rawDesc), len(file_test_bus_proto_rawDesc)))
	})
	return file_test_bus_proto_rawDescData
}

var file_test_bus_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_test_bus_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_test_bus_proto_goTypes = []any{
	(EventType)(0),       // 0: com.netcracker.mesh.v3.test.bus.EventType
	(*Topic)(nil),        // 1: com.netcracker.mesh.v3.test.bus.Topic
	(*Event)(nil),        // 2: com.netcracker.mesh.v3.test.bus.Event
	(*RawBytesData)(nil), // 3: com.netcracker.mesh.v3.test.bus.RawBytesData
	(*Empty)(nil),        // 4: com.netcracker.mesh.v3.test.bus.Empty
	(*anypb.Any)(nil),    // 5: google.protobuf.Any
}
var file_test_bus_proto_depIdxs = []int32{
	0, // 0: com.netcracker.mesh.v3.test.bus.Event.eventType:type_name -> com.netcracker.mesh.v3.test.bus.EventType
	5, // 1: com.netcracker.mesh.v3.test.bus.Event.data:type_name -> google.protobuf.Any
	1, // 2: com.netcracker.mesh.v3.test.bus.TestEventBus.Subscribe:input_type -> com.netcracker.mesh.v3.test.bus.Topic
	4, // 3: com.netcracker.mesh.v3.test.bus.TestEventBus.GetLastSnapshot:input_type -> com.netcracker.mesh.v3.test.bus.Empty
	2, // 4: com.netcracker.mesh.v3.test.bus.TestEventBus.Subscribe:output_type -> com.netcracker.mesh.v3.test.bus.Event
	2, // 5: com.netcracker.mesh.v3.test.bus.TestEventBus.GetLastSnapshot:output_type -> com.netcracker.mesh.v3.test.bus.Event
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_test_bus_proto_init() }
func file_test_bus_proto_init() {
	if File_test_bus_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_test_bus_proto_rawDesc), len(file_test_bus_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_test_bus_proto_goTypes,
		DependencyIndexes: file_test_bus_proto_depIdxs,
		EnumInfos:         file_test_bus_proto_enumTypes,
		MessageInfos:      file_test_bus_proto_msgTypes,
	}.Build()
	File_test_bus_proto = out.File
	file_test_bus_proto_goTypes = nil
	file_test_bus_proto_depIdxs = nil
}
