package org.qubership.remesh;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.Test;
import org.qubership.remesh.handler.MeshResourceFragment;
import org.qubership.remesh.handler.MeshResourceFragmentParser;
import org.qubership.remesh.handler.Resource;
import org.qubership.remesh.handler.MeshResourceRouter;
import org.qubership.remesh.serialization.ResourceSerializer;
import org.qubership.remesh.util.ObjectMapperProvider;
import org.qubership.remesh.validation.ResourceValidator;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

class TransformerServiceTest {

    @Test
    void writesHandledResourcesToNewFile() throws IOException {
        Path dir = Files.createTempDirectory("remesh-test");
        Path input = dir.resolve("resource.yaml");
        Files.writeString(input, "apiVersion: demo/v1\nkind: Mesh\nsubKind: Demo");

        ObjectMapper mapper = ObjectMapperProvider.getMapper();

        MeshResourceFragmentParser fragmentParser = new MeshResourceFragmentParser(null, null) {
            @Override
            public MeshResourceFragment parse(String rawDoc, int index) {
                try {
                    JsonNode node = mapper.readTree("apiVersion: core.netcracker.com/v1\nkind: Mesh\nsubKind: Demo\nspec:\n  foo: bar");
                    return MeshResourceFragment.create(index, node, null);
                } catch (Exception e) {
                    return null;
                }
            }
        };

        RecordingRouter router = new RecordingRouter();
        NoopValidator validator = new NoopValidator();

        TransformerService transformerService = new TransformerService(fragmentParser, router, validator, new ResourceSerializer(mapper));

        transformerService.transform(dir, true);

        Path oldFile = dir.resolve("resource.yaml");
        Path output = dir.resolve("resource-autogenerated.yaml");
        assertTrue(Files.exists(oldFile));
        assertTrue(Files.exists(output));
        String content = Files.readString(output);
        assertTrue(content.contains("DemoResource"));
        assertTrue(content.startsWith("{{- if eq .Values.SERVICE_MESH_TYPE \"ISTIO\" }}"), "Output should start with Helm ISTIO condition");
        assertTrue(content.endsWith("{{- end }}\n"), "Output should end with Helm end condition");
        assertEquals(1, router.handledDocuments);
        assertEquals(1, validator.validatedResources);
    }

    private static class RecordingRouter extends MeshResourceRouter {
        private int handledDocuments = 0;

        @Override
        public List<Resource> route(MeshResourceFragment fragment, Map<String, Object> config) {
            handledDocuments++;
            List<Resource> resources = new ArrayList<>();
            resources.add(new DemoResource());
            return resources;
        }
    }

    private static class NoopValidator extends ResourceValidator {
        private int validatedResources = 0;

        @Override
        public void validateResource(Resource resource) {
            validatedResources++;
        }
    }

    private static class DemoResource implements Resource {
        @Override
        public String getApiVersion() {
            return "demo/v1";
        }

        @Override
        public String getKind() {
            return "DemoResource";
        }

        @Override
        public String getRawMetadata() {
            return null;
        }

        @Override
        public void setRawMetadata(String rawMetadata) {
        }
    }
}
